### ISSUE TITLE
Slidescale

### ISSUE THREAD

**Issue by neginmz** [JAQuent/functions-for-matlab#2]
Thanks a lot Jörn for your nice code and the great help, however, I need to make a few changes to it. I'm using this as a subjective visibility scale( from 0 to 100) but in my experiment, the cursor should take only 21 positions on the scale that divided the scale by steps of 5% visibility(0,5,10,15...100)) and its initial position should be random at each of these positions.  Any help would be greatly appreciated.

**Comment by JAQuent** [comment]
Hey neginmz, thank you so much for your interest. What you have in mind is not difficult at all. 

Let's start with the easiest change. To have a random position you have to get rid of these lines:
`if strcmp(startPosition, 'right')
    x = globalRect(3)*scalaLength;
elseif strcmp(startPosition, 'center')
    x = globalRect(3)/2;
elseif strcmp(startPosition, 'left')
    x = globalRect(3)*(1-scalaLength);
else
    error('Only right, center and left are possible start positions');
end`

and add something like this:
`x = randi([rect(3)*scalaLength rect(3)*(1-scalaLength)],1,1);`
Now, the mouse position varies randomly between `rect(3)*scalaLength`  and `rect(3)*(1-scalaLength)`, which is nothing else than the boundaries of the scale.

The other things is a bit more complicated but an easy solution would be something like this. In the original code the slide is confined to the boundaries by resetting the x-value to  `rect(3)*scalaLength` or  `rect(3)*(1-scalaLength)` as soon as the cursor would go beyond the scale.  
See:
`    if x > rect(3)*scalaLength
        x = rect(3)*scalaLength;
    elseif x < rect(3)*(1-scalaLength)
        x = rect(3)*(1-scalaLength);
end` 

You could just add more conditions. So you find the number of pixels that make the scale and define the intervalls. Everything from 0 % to 2.5% is set to `x = rect(3)*(1-scalaLength)` (i.e. to the beginning of the scale) and everything >2.5% to 7.5% is set to the 5 % position of the scale which is the number of pixels of the scale times 0.05 + plus `rect(3)*(1-scalaLength)`. 

I have not tried my suggestions. So, it could be that this does not work at all. If it does not work, I will try to help. Anyway, I hope that my suggestions will help you with your work.

**Comment by JAQuent** [comment]
If you run in to problems, you can so decouple the position of the mouse and the slider by
`sliderPosition = x;` and using slider position to construct your intervalls.

**Comment by neginmz** [comment]
Thank you very much, I try it out and I will write you back if I face a problem

**Comment by neginmz** [comment]
I think I need your help cause I'm new to Psychtoolbox and I can't get any of these outputs although I got your concept! Thank you indeed

**Comment by JAQuent** [comment]
If you want, you can show me what you got so far.

**Comment by neginmz** [comment]
Already stuck at the beginning of the easy one, I only get the grey background as output when I set the start position at random. 
if strcmp(startPosition, 'right')
    x = rect(3)*scalaLength;
elseif strcmp(startPosition, 'center')
    x = center(1);
elseif strcmp(startPosition, 'left')
    x = rect(3)*(1-scalaLength);
    
elseif strcmp(startPosition, 'random')
    x = randi([rect(3)*(1-scalaLength),rect(3)*scalaLength],1);
else
    error('Only right, center and left are possible start positions');
end

**Comment by neginmz** [comment]
I fixed the intervals as you said. And it works:) 

distance=sqrt(((rect(3)*scalaLength)-(rect(3)*(1-scalaLength)))^2 + ((rect(4)*scalaPosition - lineLength)-(rect(4)*scalaPosition + lineLength))^2);

midTick    = [center(1) rect(4)*scalaPosition - lineLength - 5 center(1) rect(4)*scalaPosition  + lineLength + 5];
leftTick   = [rect(3)*(1-scalaLength) rect(4)*scalaPosition - lineLength rect(3)*(1-scalaLength) rect(4)*scalaPosition  + lineLength];
interval5  = [distance*0.05+rect(3)*(1-scalaLength) rect(4)*scalaPosition - lineLength distance*0.05+rect(3)*(1-scalaLength) rect(4)*scalaPosition  + lineLength];
interval10 = [distance*0.1+rect(3)*(1-scalaLength) rect(4)*scalaPosition - lineLength distance*0.1+rect(3)*(1-scalaLength) rect(4)*scalaPosition  + lineLength];
interval15 = [distance*0.15+rect(3)*(1-scalaLength) rect(4)*scalaPosition - lineLength distance*0.15+rect(3)*(1-scalaLength) rect(4)*scalaPosition  + lineLength];
interval20 = [distance*0.2+rect(3)*(1-scalaLength) rect(4)*scalaPosition - lineLength distance*0.2+rect(3)*(1-scalaLength) rect(4)*scalaPosition  + lineLength];
interval25 = [distance*0.25+rect(3)*(1-scalaLength) rect(4)*scalaPosition - lineLength distance*0.25+rect(3)*(1-scalaLength) rect(4)*scalaPosition  + lineLength];
interval30 = [distance*0.3+rect(3)*(1-scalaLength) rect(4)*scalaPosition - lineLength distance*0.3+rect(3)*(1-scalaLength) rect(4)*scalaPosition  + lineLength];
.....

**Comment by neginmz** [comment]
and the conditions also:
if x > rect(3)*(1-scalaLength)+1 && x < distance*0.05+rect(3)*(1-scalaLength)
       x = distance*0.05+rect(3)*(1-scalaLength);
    end 
    if x > distance*0.05+rect(3)*(1-scalaLength) && x < distance*0.1+rect(3)*(1-scalaLength)
       x = distance*0.1+rect(3)*(1-scalaLength);
    end
    if x > distance*0.1+rect(3)*(1-scalaLength) && x < distance*0.15+rect(3)*(1-scalaLength)
       x = distance*0.15+rect(3)*(1-scalaLength);
    end
    if x > distance*0.15+rect(3)*(1-scalaLength) && x < distance*0.2+rect(3)*(1-scalaLength)
       x = distance*0.2+rect(3)*(1-scalaLength);
    end
    if x > distance*0.2+rect(3)*(1-scalaLength) && x < distance*0.25+rect(3)*(1-scalaLength)
       x = distance*0.25+rect(3)*(1-scalaLength);
    end
    if x > distance*0.25+rect(3)*(1-scalaLength) && x < distance*0.3+rect(3)*(1-scalaLength)
       x = distance*0.3+rect(3)*(1-scalaLength);
...
...
Thank you very much for your help once again.

**Comment by JAQuent** [comment]
I am really happy that it works. Thank you for the appreciation
